FROM python:3.11
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
ARG USER_ID
ARG GROUP_ID

RUN groupadd -g "$GROUP_ID" app && useradd -u "$USER_ID" -r -g "$GROUP_ID" -s /sbin/nologin app

WORKDIR /app

# libgdal-dev version must be greater or equal to python GDAL library
COPY requirements/requirements.txt requirements/requirements-test.txt /app
RUN apt update && apt install -y libgdal-dev
RUN pip install -r requirements.txt -r requirements-test.txt GDAL==`gdal-config --version` --quiet

COPY docker-entrypoint.sh /app

USER app

EXPOSE 8000
ENTRYPOINT ["./docker-entrypoint.sh"]