from typing import Dict, TypeVar

from backend.areas.models import AreaParser
from backend.areas.parsers import EpodgikAreaParser, Geoportal2AreaParser

BaseAreaParser = TypeVar('BaseAreaParser', bound=AreaParser)
all_counties: Dict[str, BaseAreaParser] = {
    # 02 – "dolnośląskie"
    '0203': Geoportal2AreaParser(name='głogowski', url_code='glogow'),
    '0204': Geoportal2AreaParser(name='górowski', url_code='gora'),
    '0205': Geoportal2AreaParser(name='jaworski', url_code='jawor'),
    # 04 – "kujawsko-pomorskie"
    '0408': Geoportal2AreaParser(name='lipnowski', url_code='lipno'),
    '0411': Geoportal2AreaParser(name='radziejowski', url_code='radziejow'),
    '0412': Geoportal2AreaParser(name='rypiński', url_code='rypin'),
    '0417': Geoportal2AreaParser(name='wąbrzeski', url_code='wabrzezno'),
    '0418': Geoportal2AreaParser(name='włocławski', url_code='wloclawek'),
    # 06 – "lubelskie"
    '0601': Geoportal2AreaParser(name='bialski', url_code='powiatbialski'),
    '0602': Geoportal2AreaParser(name='biłgorajski', url_code='bilgorajski'),
    '0604': Geoportal2AreaParser(name='hrubieszowski', url_code='hrubieszow'),
    '0605': Geoportal2AreaParser(name='janowski', url_code='janow'),
    '0606': Geoportal2AreaParser(name='krasnostawski', url_code='powiatkrasnostawski'),
    '0608': Geoportal2AreaParser(name='lubartowski', url_code='powiatlubartowski'),
    '0609': Geoportal2AreaParser(name='lubelski', url_code='powiatlubelski'),
    '0610': Geoportal2AreaParser(name='łęczyński', url_code='leczna'),
    '0611': Geoportal2AreaParser(name='łukowski', url_code='powiatlukowski'),
    '0612': Geoportal2AreaParser(name='opolski', url_code='opolelubelskie'),
    '0613': Geoportal2AreaParser(name='parczewski', url_code='parczew'),
    '0614': Geoportal2AreaParser(name='puławski', url_code='pulawy'),
    '0615': Geoportal2AreaParser(name='radzyński', url_code='powiatradzynski'),
    '0616': Geoportal2AreaParser(name='rycki', url_code='ryki'),
    '0617': Geoportal2AreaParser(name='świdnicki', url_code='powiatswidnik'),
    '0618': Geoportal2AreaParser(name='tomaszowski', url_code='tomaszowlubelski'),
    '0619': EpodgikAreaParser(name='włodawski', url_code='wlodawa'),
    # 0620 it works but cannot find any building data
    # '0620': Geoportal2AreaParser(name='zamojski', url_code='powiatzamojski'),
    '0661': Geoportal2AreaParser(name='miasto Biała Podlaska', url_code='bialapodlaska'),
    '0662': EpodgikAreaParser(name='miasto Chełm', url_code='mchelm'),
    '0664': Geoportal2AreaParser(name='miasto Zamość', url_code='zamosc'),
    # 08 – "lubuskie"
    '0801': Geoportal2AreaParser(name='gorzowski', url_code='powiatgorzowski'),
    '0803': Geoportal2AreaParser(name='międzyrzecki', url_code='powiat-miedzyrzecki'),
    '0805': Geoportal2AreaParser(name='słubicki', url_code='slubice'),
    '0806': Geoportal2AreaParser(name='strzelecko-drezdenecki', url_code='fsd'),
    '0807': Geoportal2AreaParser(name='sulęciński', url_code='sulecin'),
    '0811': Geoportal2AreaParser(name='żarski', url_code='zary'),
    '0812': Geoportal2AreaParser(name='wschowski', url_code='wschowa'),
    # 10 – "łódzkie"
    # 12 – "małopolskie"
    # 14 – "mazowieckie"
    '1411': Geoportal2AreaParser(name='makowski', url_code='makow'),
    '1412': EpodgikAreaParser(name='miński', url_code='minsk'),
    '1413': Geoportal2AreaParser(name='mławski', url_code='powiatmlawski'),
    '1414': Geoportal2AreaParser(name='nowodworski', url_code='nowodworski'),
    '1415': Geoportal2AreaParser(name='ostrołęcki', url_code='powiatostrolecki'),
    '1416': Geoportal2AreaParser(name='ostrowski', url_code='ostrowmaz'),
    '1417': Geoportal2AreaParser(name='otwocki', url_code='powiat-otwocki'),
    '1418': EpodgikAreaParser(name='piaseczyński', url_code='piaseczno'),
    '1419': Geoportal2AreaParser(name='płocki', url_code='powiat-plock'),
    '1420': Geoportal2AreaParser(name='płoński', url_code='plonski'),
    '1421': EpodgikAreaParser(name='pruszkowski', url_code='pruszkow'),
    '1422': Geoportal2AreaParser(name='przasnyski', url_code='przasnysz'),
    '1423': Geoportal2AreaParser(name='przysuski', url_code='przysucha'),
    '1424': Geoportal2AreaParser(name='pułtuski', url_code='powiatpultuski'),
    '1425': Geoportal2AreaParser(name='radomski', url_code='radom'),
    '1426': Geoportal2AreaParser(name='siedlecki', url_code='powiatsiedlecki'),
    '1427': Geoportal2AreaParser(name='sierpecki', url_code='sierpc'),
    '1428': Geoportal2AreaParser(name='sochaczewski', url_code='sochaczew'),
    '1429': Geoportal2AreaParser(name='sokołowski', url_code='powiat-sokolowski'),
    '1430': Geoportal2AreaParser(name='szydłowiecki', url_code='szydlowiecpowiat'),
    '1433': EpodgikAreaParser(name='węgrowski', url_code='wegrow'),
    '1434': EpodgikAreaParser(name='wołomiński', url_code='wolomin'),
    '1435': Geoportal2AreaParser(name='wyszkowski', url_code='powiat-wyszkowski'),
    '1436': Geoportal2AreaParser(name='zwoleński', url_code='zwolenpowiat'),
    '1437': Geoportal2AreaParser(name='żuromiński', url_code='zuromin-powiat'),
    '1438': EpodgikAreaParser(name='żyrardowski', url_code='zyrardow'),
    '1461': Geoportal2AreaParser(name='miasto Ostrołęka', url_code='ostroleka'),
    '1464': Geoportal2AreaParser(name='miasto Siedlce', url_code='siedlce'),
    # 16 – "opolskie"
    # 18 – "podkarpackie"
    '1803': Geoportal2AreaParser(name='dębicki', url_code='debica'),
    '1806': Geoportal2AreaParser(name='kolbuszowski', url_code='kolbuszowa'),
    '1808': Geoportal2AreaParser(name='leżajski', url_code='lezajsk'),
    '1809': Geoportal2AreaParser(name='lubaczowski', url_code='lubaczow'),
    '1810': Geoportal2AreaParser(name='łańcucki', url_code='lancut'),
    '1811': Geoportal2AreaParser(name='mielecki', url_code='mielec'),
    '1812': Geoportal2AreaParser(name='niżański', url_code='powiat-nisko'),
    '1813': Geoportal2AreaParser(name='przemyski', url_code='powiat-przemysl'),
    '1815': Geoportal2AreaParser(name='ropczycko-sędziszowski', url_code='spropczyce'),
    '1816': Geoportal2AreaParser(name='rzeszowski', url_code='powiatrzeszowski'),
    '1818': Geoportal2AreaParser(name='stalowowolski', url_code='stalowawola'),
    '1819': Geoportal2AreaParser(name='strzyżowski', url_code='strzyzowski'),
    '1820': Geoportal2AreaParser(name='tarnobrzeski', url_code='tarnobrzeski'),
    '1821': Geoportal2AreaParser(name='leski', url_code='lesko'),
    '1862': Geoportal2AreaParser(name='miasto Przemyśl', url_code='przemysl'),
    '1864': Geoportal2AreaParser(name='miasto Tarnobrzeg', url_code='tarnobrzeg'),
    # 20 – "podlaskie"
    '2001': Geoportal2AreaParser(name='augustowski', url_code='augustowski'),
    '2002': Geoportal2AreaParser(name='białostocki', url_code='bialystok'),
    '2003': Geoportal2AreaParser(name='bielski', url_code='powiatbielski'),
    '2004': Geoportal2AreaParser(name='grajewski', url_code='starostwograjewo'),
    '2005': Geoportal2AreaParser(name='hajnowski', url_code='hajnowka'),
    '2008': Geoportal2AreaParser(name='moniecki', url_code='monki'),
    '2009': Geoportal2AreaParser(name='sejneński', url_code='sejny'),
    '2011': Geoportal2AreaParser(name='sokólski', url_code='powiatsokolski'),
    '2013': Geoportal2AreaParser(name='wysokomazowiecki', url_code='wysokomazowiecki'),
    '2014': Geoportal2AreaParser(name='zambrowski', url_code='powiatzambrowski'),
    # 22 – "pomorskie"
    '2215': EpodgikAreaParser(name='wejherowski', url_code='wejherowo'),
    # 24 – "śląskie"
    '2403': Geoportal2AreaParser(name='cieszyński', url_code='cieszyn'),
    '2404': Geoportal2AreaParser(name='częstochowski', url_code='czestochowa'),
    '2411': Geoportal2AreaParser(name='raciborski', url_code='raciborz'),
    '2412': Geoportal2AreaParser(name='rybnicki', url_code='rybnik'),
    '2467': Geoportal2AreaParser(name='miasto Jastrzębie-Zdrój', url_code='jastrzebie'),
    '2472': Geoportal2AreaParser(name='miasto Ruda Śląska', url_code='rudaslaska'),
    '2474': Geoportal2AreaParser(name='miasto Siemianowice Śląskie', url_code='siemianowice'),
    '2476': Geoportal2AreaParser(name='miasto Świętochłowice', url_code='swietochlowice'),
    # 26 – "świętokrzyskie"
    '2602': Geoportal2AreaParser(name='jędrzejowski', url_code='jedrzejow'),
    '2603': Geoportal2AreaParser(name='kazimierski', url_code='kazimierzaw'),
    '2605': Geoportal2AreaParser(name='konecki', url_code='konskie'),
    '2606': Geoportal2AreaParser(name='opatowski', url_code='opatow'),
    '2607': Geoportal2AreaParser(name='ostrowiecki', url_code='ostrowiec'),
    '2608': Geoportal2AreaParser(name='pińczowski', url_code='pinczow'),
    '2609': Geoportal2AreaParser(name='sandomierski', url_code='sandomierz'),
    '2610': Geoportal2AreaParser(name='skarżyski', url_code='skarzysko'),
    '2611': Geoportal2AreaParser(name='starachowicki', url_code='starachowice'),
    '2612': Geoportal2AreaParser(name='staszowski', url_code='staszow'),
    '2613': Geoportal2AreaParser(name='włoszczowski', url_code='wloszczowa'),
    # 28 – "warmińsko-mazurskie"
    '2801': Geoportal2AreaParser(name='bartoszycki', url_code='powiatbartoszyce'),
    '2802': Geoportal2AreaParser(name='braniewski', url_code='powiat-braniewo'),
    '2803': Geoportal2AreaParser(name='działdowski', url_code='powiatdzialdowski'),
    '2805': Geoportal2AreaParser(name='ełcki', url_code='powiatelk'),
    '2806': EpodgikAreaParser(name='giżycki', url_code='gizycko'),
    '2807': Geoportal2AreaParser(name='iławski', url_code='ilawa'),
    '2808': Geoportal2AreaParser(name='kętrzyński', url_code='powiatketrzynski'),
    '2809': Geoportal2AreaParser(name='lidzbarski', url_code='powiatlidzbarski'),
    '2810': EpodgikAreaParser(name='mrągowski', url_code='mragowo'),
    '2811': Geoportal2AreaParser(name='nidzicki', url_code='powiatnidzicki'),
    '2812': Geoportal2AreaParser(name='nowomiejski', url_code='powiat-nowomiejski'),
    '2813': Geoportal2AreaParser(name='olecki', url_code='olecko'),
    '2814': Geoportal2AreaParser(name='olsztyński', url_code='powiatolsztynski'),
    '2815': Geoportal2AreaParser(name='ostródzki', url_code='ostroda'),
    '2816': Geoportal2AreaParser(name='piski', url_code='powiatpiski'),
    '2817': Geoportal2AreaParser(name='szczycieński', url_code='szczytno'),
    '2818': Geoportal2AreaParser(name='gołdapski', url_code='powiatgoldap'),
    '2819': EpodgikAreaParser(name='węgorzewski', url_code='wegorzewo'),
    # 30 – "wielkopolskie"
    '3007': Geoportal2AreaParser(name='kaliski', url_code='kalisz'),
    '3010': Geoportal2AreaParser(name='koniński', url_code='konin'),
    '3014': EpodgikAreaParser(name='międzychodzki', url_code='miedzychod'),
    # 32 – "zachodniopomorskie"
}
# Few exception which counties are already defined but these communes has own servive for the data
communes = {
    '2403011': Geoportal2AreaParser(name='cieszyn', url_code='miastocieszyn'),
}
all_areas = all_counties | communes
