"""Add AreaImport model

Revision ID: 2aa2de043ff7
Revises: 3f695856ad1a
Create Date: 2024-10-27 21:13:43.199968

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aa2de043ff7'
down_revision: Union[str, None] = '3f695856ad1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'area_imports',
        sa.Column('id', sa.BigInteger(), nullable=False),
        sa.Column('teryt', sa.String(length=8), nullable=False),
        sa.Column('start_at', sa.DateTime(), nullable=False),
        sa.Column('end_at', sa.DateTime(), nullable=False),
        sa.Column(
            'result_status',
            sa.Enum(
                'SUCCESS',
                'DOWNLOADING_ERROR',
                'PARSING_ERROR',
                'EMPTY_DATA_ERROR',
                name='resultstatus',
            ),
            nullable=False,
        ),
        sa.Column('building_count', sa.BigInteger(), nullable=False),
        sa.Column('has_building_type', sa.Boolean(), nullable=False),
        sa.Column('has_building_levels', sa.Boolean(), nullable=False),
        sa.Column('has_building_levels_undg', sa.Boolean(), nullable=False),
        sa.CheckConstraint('building_count >= 0'),
        sa.CheckConstraint('end_at > start_at'),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('area_imports')
    # ### end Alembic commands ###
